apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-multi.com
  dnsNames:
    - theboston3dproject.com
    - www.theboston3dproject.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - theboston3dproject.com
          - www.theboston3dproject.com